services:
  app:
    container_name: lafs-web
    restart: always
    build: .
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - lafs-net

networks:
  lafs-net:
    external: true
